[package]
name = "sample"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# TOML (Tom’s Obvious, Minimal Language)
[dependencies]
rand = "0.8.5"